CREATE TABLE PESSOA (
    Email VARCHAR(250),
    ID SERIAL PRIMARY KEY,
    Nome VARCHAR(250),
    Senha VARCHAR(50)
);

CREATE TABLE Contato (
    Contato_Usuario VARCHAR(250),
    ID INT NOT NULL,
    Codigo_contato INT NOT NULL
);

CREATE TABLE USUARIO (
    Data_Nasc DATE,
    Data_de_inscricao DATE NOT NULL DEFAULT CURRENT_DATE,
    Genero CHAR(1)
)INHERITS (PESSOA);

CREATE TABLE ADMINISTRADOR (
    CPF INT NOT NULL,
    Matricula_funcional VARCHAR(25)
)INHERITS (PESSOA);

CREATE TABLE TIPO_DE_CONTATO (
    Tipo_Contato VARCHAR(150),
    Codigo_contato SERIAL PRIMARY KEY
);

CREATE TABLE ROTA (
    ID_Rota SERIAL PRIMARY KEY,
    Apelido VARCHAR(250),
    ID_Usuario INT NOT NULL
);

CREATE TABLE LOCAL (
    ID_Local SERIAL PRIMARY KEY,
    ID_Usuario INT NOT NULL,
    Apelido VARCHAR(250),
    ID_Endereco INT NOT NULL
);

CREATE TABLE ENDERECO (
    ID_Endereco SERIAL PRIMARY KEY,
    Rua VARCHAR(250),
    Codigo_bairro INT NOT NULL
);

CREATE TABLE CAMINHO (
    Ordem INT NOT NULL,
    ID_Endereco INT NOT NULL,
    ID_Rota INT NOT NULL
);

CREATE TABLE ITEM_ROUBADO (
    Qtd INT,
    Item VARCHAR(250),
    ID_Boletim INT NOT NULL
);

CREATE TABLE TIPO_DE_LOCAL (
    Tipo_local VARCHAR(150),
    Codigo SERIAL PRIMARY KEY
);

CREATE TABLE BOLETIM (
    Data DATE,
    Hora VARCHAR(9),
    Crime VARCHAR(10),
    ID_Boletim INT NOT NULL PRIMARY KEY,
    ID_Endereco INT NOT NULL,
    Codigo INT,
    ID INT,
    Origem BOOLEAN
    );


CREATE TABLE MUNICIPIO (
    Codigo_municipio SERIAL PRIMARY KEY,
    Nome_municipio VARCHAR(250)
);

CREATE TABLE BAIRRO (
    Codigo_bairro SERIAL PRIMARY KEY,
    Nome_bairro VARCHAR(250),
    Codigo_municipio INT NOT NULL
);

CREATE TABLE TIPO_DE_CRIME(
	CODIGO_CRIME VARCHAR(10),
	CRIME VARCHAR(150),
	ESPECIFICACAO VARCHAR(250)
);

ALTER TABLE CONTATO ADD FOREIGN KEY(Codigo_contato) REFERENCES TIPO_DE_CONTATO (Codigo_contato);
ALTER TABLE CONTATO ADD FOREIGN KEY(ID) REFERENCES PESSOA (ID);
ALTER TABLE CAMINHO ADD FOREIGN KEY(ID_Endereco) REFERENCES ENDERECO (ID_Endereco);
ALTER TABLE CAMINHO ADD FOREIGN KEY(ID_Rota) REFERENCES ROTA (ID_Rota);
ALTER TABLE BOLETIM ADD FOREIGN KEY(ID_Endereco) REFERENCES ENDERECO (ID_Endereco);
ALTER TABLE BOLETIM ADD FOREIGN KEY(Codigo) REFERENCES TIPO_DE_LOCAL (Codigo);
ALTER TABLE BOLETIM ADD FOREIGN KEY(ID) REFERENCES PESSOA (ID);
ALTER TABLE BAIRRO ADD FOREIGN KEY (CODIGO_MUNICIPIO) REFERENCES MUNICIPIO(CODIGO_MUNICIPIO)
ALTER TABLE TIPO_DE_CRIME ADD FOREIGN KEY(CODIGO_CRIME) REFERENCES BOLETIM (CRIME);
ALTER TABLE Contato ADD FOREIGN KEY(Codigo_contato) REFERENCES TIPO_DE_CONTATO (Codigo_contato);
ALTER TABLE LOCAL ADD FOREIGN KEY(ID_Endereco) REFERENCES ENDERECO (ID_Endereco);
ALTER TABLE ENDERECO ADD FOREIGN KEY(Codigo_bairro) REFERENCES BAIRRO (Codigo_bairro);
ALTER TABLE ITEM_ROUBADO ADD FOREIGN KEY(ID_Boletim) REFERENCES BOLETIM (ID_Boletim);
ALTER TABLE BAIRRO ADD FOREIGN KEY(Codigo_municipio) REFERENCES MUNICIPIO (Codigo_municipio);



/* INSERÇÃO DE DADOS */

INSERT INTO USUARIO (NOME, SENHA, EMAIL, DATA_NASC, GENERO) VALUES
('JOÃO', '123456','joaostn@gmail.com','1990/07/19','M'),
('JOSÉ MARIA', 'KK1234','jsmaria@gmail.com','1961/05/29','M'),
('GERALDO', 'VNSA321','jsgeraldo@gmail.com','1972/12/29','M'),
('JULIANA','OI908','julianayks@gmail.com','1997/07/19','F'),
('MARCOS','NXZERO45','marquinhos@hotmail.com','1990/07/16','M'),
('OLGA','PEIXE','olgaks@hotmail.com','1961/05/24','F'),
('MARIANA','mArazul','marianabela@gmail.com','2000/12/25','F'),
('JOÃO VICTOR','jv3786','joaovictor@hotmail.com','1997/10/01','M');

INSERT INTO ADMINISTRADOR (NOME, SENHA, EMAIL, CPF, MATRICULA_FUNCIONAL) VALUES
('ANDRE','98765432','andre.barbosa@gmail.com',123456789,'34567123');

INSERT INTO TIPO_DE_CONTATO (TIPO_CONTATO) VALUES
('Telefone'),
('Celular'),
('Facebook');

INSERT INTO CONTATO (CONTATO_USUARIO, ID ,CODIGO_CONTATO) VALUES
('32432566',1,1),
('32527219',2,1),
('facebook.com/josemaria',2,3),
('998763569',3,2),
('facebook.com/julianayuri',4,3),
('32451995',5,1),
('995070917',5,2),
('32522993',7,1),
('998001755',8,2);

INSERT INTO LOCAL (ID_USUARIO, APELIDO, ID_ENDERECO) VALUES
(8,'Casa',78),
(8,'Casa da mãe',17),
(1,'Academia',1087),
(8,'Faculdade', 503),
(5,'Trabalho',23070),
(4,'Casa',11765),
(2,'Casa',4987),
(2,'Hotel',3369),
(7,'Shopping',20176);

INSERT INTO ROTA (APELIDO, ID_USUARIO) VALUES
('Trabalho',5),
('Casa da mãe',8),
('Fazenda',3),
('Trabalho',2);

INSERT INTO CAMINHO (ORDEM, ID_ENDERECO, ID_ROTA) VALUES
(1,789,1),
(2,790,1),
(3,791,1),
(4,792,1)
(5,672,1),
(1,78,2),
(2,77,2),
(3,68,2),
(4,12,2),
(1,23890,3),
(2,23789,3),
(3,21564,3),
(1,4987,4),
(2,5036,4),
(3,312,4),
(4,672,4),
(5,678,4),
(6,670,4);
